# Generated by Django 4.2 on 2023-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='city',
            field=models.CharField(blank=True),
        ),
    ]
