# Generated by Django 4.2 on 2023-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0002_docgen_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='inFile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
