# Generated by Django 4.2 on 2023-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0003_docgen_infile'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='state',
            field=models.CharField(blank=True),
        ),
    ]
