# Generated by Django 4.2 on 2023-05-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0004_docgen_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgen',
            name='inFile',
            field=models.CharField(max_length=200),
        ),
    ]
