# Generated by Django 4.2 on 2023-05-25 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0005_alter_docgen_infile'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
