# Generated by Django 4.2 on 2023-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0006_docgen_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docgen',
            name='inFile',
        ),
    ]
