# Generated by Django 4.2 on 2023-05-26 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0007_remove_docgen_infile'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='outFileType',
            field=models.CharField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='pricingType',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
