# Generated by Django 4.2 on 2023-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0008_docgen_outfiletype_docgen_pricingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='inFile',
            field=models.FileField(default=4, upload_to=''),
            preserve_default=False,
        ),
    ]
