# Generated by Django 4.2 on 2023-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0009_docgen_infile'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='conAddress',
            field=models.CharField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='conEmail',
            field=models.CharField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='conName',
            field=models.CharField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='conPH',
            field=models.CharField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='conTitle',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
    ]
