# Generated by Django 4.2 on 2023-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0010_docgen_conaddress_docgen_conemail_docgen_conname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgen',
            name='bdExtension',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='bdName',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='bdPH',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docgen',
            name='bdTitle',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
    ]
