# Generated by Django 4.2 on 2023-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0013_alter_docgen_bdextension_alter_docgen_bdname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgen',
            name='inFile',
            field=models.BinaryField(),
        ),
    ]
