# Generated by Django 4.2 on 2023-05-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0014_alter_docgen_infile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgen',
            name='inFile',
            field=models.FileField(upload_to=''),
        ),
    ]
