# Generated by Django 4.2.4 on 2023-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
