# Generated by Django 4.2.4 on 2023-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pss", "0002_customer_address_customer_city_customer_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("NC", "North Carolina"), ("SC", "South Carolina")],
                max_length=2,
                null=True,
            ),
        ),
    ]
