from django.db import models
from datetime import datetime


class Docgen(models.Model):
    inFile = models.URLField(max_length=None, blank=False)
    city = models.CharField(blank=True)
    state = models.CharField(blank=True)
    entity = models.CharField(max_length=200)
    outFileType = models.CharField(blank=False)
    pricingType = models.CharField(blank=False)
    conName = models.CharField(blank=True)
    conTitle = models.CharField(blank=True)
    conPH = models.CharField(blank=True)
    conAddress = models.CharField(blank=True)
    conEmail = models.CharField(blank=True)
    bdName = models.CharField(blank=True)
    bdTitle = models.CharField(blank=True)
    bdPH = models.CharField(blank=True)
    bdExtension = models.CharField(blank=True)
    projName = models.CharField(blank=True)
    pprNum = models.CharField(blank=True)
    poNum = models.CharField(blank=True)
    specs = models.CharField(blank=True)
    dnrCost = models.FloatField(blank=True)
    smCost = models.FloatField(blank=True)
    mdCost = models.FloatField(blank=True)
    lgCost = models.FloatField(blank=True)
    curbCost = models.FloatField(blank=True)
    segways = models.CharField(blank=True)
    safetyIncidents = models.CharField(blank=True)
    knownDaysToFinish = models.CharField(blank=True)
    minDaysToFinish = models.CharField(blank=True)
    maxDaysToFinish = models.CharField(blank=True)
    techs = models.CharField(blank=True)
    pssMin = models.CharField(blank=True)
    woLoc = models.CharField(blank=False)
    mapData = models.CharField(blank=True)

    creation_date = models.DateTimeField(default=datetime.now, blank=True)

